// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ifzcozfwpxacgxhjoglv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlmemNvemZ3cHhhY2d4aGpvZ2x2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzNjY3MzcsImV4cCI6MjA3Mzk0MjczN30.zXRkDeEpOtXmiMZjiBsMCtTUIgDOt4Sclvfh3mpEe-k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});